name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 157.173.216.164 >> ~/.ssh/known_hosts

      - name: Deploy to Hostinger via Rsync
        run: |
          rsync -avz --delete ./ u171917511@157.173.216.164:/home/u171917511/public_html/

      - name: Set Correct Permissions
        run: |
          ssh u171917511@157.173.216.164 "chmod -R 755 /home/u171917511/public_html/"

      - name: Clear Cache (Optional)
        run: |
          ssh u171917511@157.173.216.164 "rm -rf /home/u171917511/public_html/wp-content/cache/*"