name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 157.173.216.164 >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to Hostinger via Rsync
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ u171917511@157.173.216.164:/home/u171917511/public_html/

      - name: Set Correct Permissions
        run: |
          ssh -o StrictHostKeyChecking=no u171917511@157.173.216.164 "chmod -R 755 /home/u171917511/public_html/"

      - name: Clear Cache (Optional)
        run: |
          ssh -o StrictHostKeyChecking=no u171917511@157.173.216.164 "wp cache flush --path=/home/u171917511/public_html/"

      - name: Complete job
        run: echo "Deployment Completed Successfully!" 
